require('dotenv').config();
const mongoose = require('mongoose');
const fs = require('fs');
const path = require('path');
const Admin = require('../models/Admin');
const User = require('../models/User');
const Venue = require('../models/Venue');
require('../models/Metadata');

/**
 * Single source of truth for demo logins.
 *
 *  - Sets the password to "password" on EVERY login: the superadmin, every
 *    restaurant owner, and every human user account (the `*@restronet-seed.local`
 *    review-author fixtures have no real login and are left alone).
 *  - Writes DEMO_LOGINS.md at the repo root — one file listing every account,
 *    its password, and (for users) its saved preferences, plus each owner's
 *    assigned restaurant.
 *
 * Each doc is saved individually so the model's pre('save') bcrypt hook runs.
 *
 * Run:  SEED_CONFIRM=yes node scripts/setAllDemoPasswords.js
 */

const NEW_PASSWORD = 'password';
const SEED_DOMAIN  = '@restronet-seed.local';
const PRICE_LABEL  = { 1: 'budget', 2: 'mid', 3: 'premium', 4: 'luxury' };

const md = (s) => (s == null || s === '' ? '—' : String(s).replace(/\|/g, '\\|'));

(async () => {
  if (process.env.SEED_CONFIRM !== 'yes') {
    console.error('Refusing to run. Re-run with:  SEED_CONFIRM=yes node scripts/setAllDemoPasswords.js');
    process.exit(1);
  }

  await mongoose.connect(process.env.MONGO_URI);
  console.log('connected');

  // ── admins (superadmin + owners) ─────────────────────────────────────────
  const admins = await Admin.find({}).select('+password').sort({ role: 1, name: 1 });
  for (const a of admins) {
    a.password = NEW_PASSWORD;
    await a.save();
  }
  console.log(`admins updated: ${admins.length}`);

  // ── users (skip the seed review fixtures) ────────────────────────────────
  const users = await User.find({ email: { $not: new RegExp(`${SEED_DOMAIN}$`, 'i') } })
    .select('+password')
    .populate('preferences.cuisines', 'name')
    .populate('preferences.tags', 'name')
    .sort({ name: 1 });
  for (const u of users) {
    u.password = NEW_PASSWORD;
    await u.save();
  }
  console.log(`users updated: ${users.length}`);

  // ── owner → assigned venue map ──────────────────────────────────────────
  const venues = await Venue.find({ owner: { $ne: null } }).select('name owner');
  const venueByOwner = new Map();
  venues.forEach((v) => {
    const k = String(v.owner);
    venueByOwner.set(k, (venueByOwner.get(k) || []).concat(v.name));
  });

  // ── build DEMO_LOGINS.md ────────────────────────────────────────────────
  const superadmins = admins.filter((a) => a.role === 'superadmin');
  const owners = admins.filter((a) => a.role === 'owner');

  const L = [];
  L.push('# RestroNet — Demo Logins');
  L.push('');
  L.push('_Generated by `restronet-backend/scripts/setAllDemoPasswords.js`._');
  L.push('_Re-run: `SEED_CONFIRM=yes node scripts/setAllDemoPasswords.js`._');
  L.push('');
  L.push('**Every account below has the password `password`.**');
  L.push('');
  L.push('| Login page | Who |');
  L.push('|---|---|');
  L.push('| user login page  | Users |');
  L.push('| admin login page | Superadmins & Restaurant Owners |');
  L.push('');

  L.push('## Superadmins  (admin login page)');
  L.push('');
  L.push('| Name | Email | Password |');
  L.push('|---|---|---|');
  superadmins.forEach((a) => L.push(`| ${md(a.name)} | ${md(a.email)} | password |`));
  L.push('');

  L.push('## Restaurant Owners  (admin login page)');
  L.push('');
  L.push('| Name | Email | Password | Assigned restaurant(s) |');
  L.push('|---|---|---|---|');
  owners.forEach((a) => {
    const vs = venueByOwner.get(String(a._id)) || [];
    L.push(`| ${md(a.name)} | ${md(a.email)} | password | ${md(vs.join(', ') || 'none assigned')} |`);
  });
  L.push('');

  L.push('## Users  (user login page)');
  L.push('');
  L.push('| Name | Email | Password | Price tier | Max distance | Cuisines | Tags | Meal types |');
  L.push('|---|---|---|---|---|---|---|---|');
  users.forEach((u) => {
    const p = u.preferences || {};
    const price = p.priceRange ? `${p.priceRange} (${PRICE_LABEL[p.priceRange] || '?'})` : '—';
    const dist = p.maxDistanceKm != null ? `${p.maxDistanceKm} km` : '—';
    const cuisines = (p.cuisines || []).map((c) => c.name).join(', ');
    const tags = (p.tags || []).map((t) => t.name).join(', ');
    const meals = (p.mealTypes || []).join(', ');
    L.push(`| ${md(u.name)} | ${md(u.email)} | password | ${md(price)} | ${md(dist)} | ${md(cuisines)} | ${md(tags)} | ${md(meals)} |`);
  });
  L.push('');

  const out = path.join(__dirname, '..', '..', 'DEMO_LOGINS.md');
  fs.writeFileSync(out, L.join('\n'));
  console.log(`wrote ${out}`);

  await mongoose.disconnect();
  console.log('done');
})().catch((e) => { console.error(e); process.exit(1); });
