/**
 * Trains local classifiers for the "soft" parts of Discover free-text query
 * intent parsing — mood, price sentiment (cheap/expensive), "near me", and
 * "top rated" — replacing aiService.parseIntent's Gemini call for these
 * fields. No network call, no API key.
 *
 * WHY A TRAINED MODEL HERE (AND NOT EVERYWHERE)
 * -----------------------------------------------
 * Extracting exact entity names (cuisine/category/tag IDs) and explicit
 * sort commands is a lookup problem — nlpParser.js already does this well
 * with fuzzy string matching against real metadata names, and training a
 * model there adds nothing over precise matching.
 *
 * Mood, price sentiment, "near me", and "top rated" are different: they're
 * expressed in endless paraphrases that don't share keywords with each
 * other ("won't break the bank" vs "cheap" — both mean the same thing but
 * share no words). A fixed keyword list only catches phrasings someone
 * thought to type in; it fails on the SAME test paraphrases a semantic
 * embedding classifier generalizes to. That's the actual argument for
 * training here — and this script's evaluation section proves it by
 * comparing the trained model against the existing keyword-rule baseline
 * on the SAME held-out sentences.
 *
 * DATA: SYNTHETIC, TEMPLATE-GENERATED, DISCLOSED
 * -------------------------------------------------
 * No labeled query log exists yet. Queries are generated by combining
 * hand-written paraphrase banks per slot (deliberately including phrasings
 * that don't overlap with the existing rule keyword lists, so the eval is
 * a fair test of generalization, not a rehash of the same words) into
 * compound sentences — mirroring how real users type ("affordable romantic
 * spot near me") rather than one slot per sentence.
 *
 * MODEL: one-vs-rest logistic regression per label, on top of the MiniLM
 * sentence embeddings already used elsewhere in this app (aiService.js).
 * Plain gradient descent with L2 regularization — no new dependency.
 */

require('dotenv').config();
const fs = require('fs');
const path = require('path');
const aiService = require('../services/aiService');
const { MOOD_KEYWORDS } = require('../services/recommendationService');

const OUT_DIR = path.join(__dirname, '..', 'ml');
const WEIGHTS_PATH = path.join(OUT_DIR, 'intent-classifier-weights.json');

// ─── 1. Paraphrase banks ────────────────────────────────────────────────
// Deliberately phrased WITHOUT reusing MOOD_KEYWORDS/rule keywords where
// possible, so the held-out test set actually measures generalization
// rather than keyword recall.
const MOOD_PHRASES = {
  romantic: ['a romantic dinner spot', 'date night place', 'candlelit dinner', 'intimate place for two',
    'perfect for an anniversary', 'cozy spot for a couple', 'somewhere special for date night'],
  'family-friendly': ['good place for family dinner', 'somewhere to bring the kids', 'family outing spot',
    'place with space for children', 'good for a family gathering', 'welcoming to little ones'],
  cafe: ['cozy coffee shop', 'place to grab a latte', 'spot for coffee and pastries', 'chill place to relax with coffee',
    'good vibes coffee shop', 'place for brunch and coffee'],
  luxury: ['fine dining experience', 'upscale restaurant', 'premium dining spot', 'gourmet restaurant',
    'high end place to eat', 'exclusive dining experience'],
  nightlife: ['place with live music', 'bar with good vibes', 'spot for drinks and music', 'late night hangout',
    'club with a dance floor', 'place to grab cocktails'],
  casual: ['laid back place to eat', 'no fuss restaurant', 'relaxed spot for a quick meal', 'simple easygoing eatery',
    'chill place to grab food', 'unpretentious restaurant'],
  'work-friendly': ['place to work with good wifi', 'spot to get work done', 'quiet place for a laptop session',
    'good for meetings over coffee', 'suitable for remote work'],
  aesthetic: ['instagrammable cafe', 'pretty place for photos', 'visually stunning restaurant',
    'place with beautiful interior', 'trendy spot for pictures'],
};

const PRICE_PHRASES = {
  cheap: ['something easy on the wallet', 'affordable place to eat', "won't break the bank", 'budget friendly spot',
    'inexpensive dinner', 'low cost meal', 'pocket friendly restaurant', 'cheap eats'],
  expensive: ['pricey but worth it', 'high end dining', 'expensive restaurant', 'premium priced place',
    'costly but excellent food', 'upscale pricing', 'top shelf dining experience'],
};

const NEAR_ME_PHRASES = ['somewhere close to me', 'restaurants nearby', 'something around here',
  'close to my location', 'within walking distance', 'spot near where I am', 'closest option available', 'around this area'];

const TOP_RATED_PHRASES = ['the best restaurants', 'highly rated spot', 'top reviewed place', 'most popular restaurant',
  'highest rated option', 'critically acclaimed restaurant', 'the finest dining around', 'most loved eatery'];

const NEUTRAL_FILLERS = ['restaurant', 'place to eat', 'dinner spot', 'somewhere to eat tonight',
  'food place', 'eatery', 'spot for lunch', 'place for dinner this weekend'];

const CUISINE_NOISE = ['italian food', 'korean bbq', 'nepali thali', 'japanese sushi', 'indian curry',
  'chinese dumplings', 'thai food']; // distractor entity words — not a predicted label

const MOOD_KEYS = Object.keys(MOOD_PHRASES);
const PRICE_KEYS = ['cheap', 'expensive'];

function pick(arr) { return arr[Math.floor(Math.random() * arr.length)]; }
function shuffle(arr) {
  const a = [...arr];
  for (let i = a.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}

/** Generates one compound synthetic query + its ground-truth label vector. */
function generateExample() {
  const parts = [];
  const label = { mood: null, price: null, isNearMe: false, isTopRated: false };

  if (Math.random() < 0.55) {
    const mood = pick(MOOD_KEYS);
    parts.push(pick(MOOD_PHRASES[mood]));
    label.mood = mood;
  }
  if (Math.random() < 0.4) {
    const price = pick(PRICE_KEYS);
    parts.push(pick(PRICE_PHRASES[price]));
    label.price = price;
  }
  if (Math.random() < 0.3) {
    parts.push(pick(NEAR_ME_PHRASES));
    label.isNearMe = true;
  }
  if (Math.random() < 0.3) {
    parts.push(pick(TOP_RATED_PHRASES));
    label.isTopRated = true;
  }
  if (Math.random() < 0.3) parts.push(pick(CUISINE_NOISE)); // noise, no label
  if (parts.length === 0) parts.push(pick(NEUTRAL_FILLERS));

  const text = shuffle(parts).join(' ').replace(/\s+/g, ' ').trim();
  return { text, label };
}

// ─── 2. Logistic regression (plain gradient descent + L2, no dependency) ─
// One-vs-rest heads here are heavily imbalanced (e.g. one mood out of 8 is
// only ~7% of rows) — plain gradient descent on imbalanced data collapses
// to "always predict the majority class". Fixed with inverse-frequency
// class weighting (same idea as sklearn's class_weight='balanced'): each
// example is weighted so the positive and negative class contribute
// equally to the gradient regardless of how rare the positive class is.
function trainLogisticRegression(rows, dim, { epochs = 600, lr = 0.5, l2 = 0.01 } = {}) {
  const posCount = rows.filter((r) => r.y === 1).length;
  const negCount = rows.length - posCount;
  const posWeight = posCount ? rows.length / (2 * posCount) : 1;
  const negWeight = negCount ? rows.length / (2 * negCount) : 1;
  const weighted = rows.map((r) => ({ ...r, w: r.y === 1 ? posWeight : negWeight }));
  const totalWeight = weighted.reduce((s, r) => s + r.w, 0);

  let weights = new Array(dim).fill(0);
  let bias = 0;

  for (let epoch = 0; epoch < epochs; epoch++) {
    const gradW = new Array(dim).fill(0);
    let gradB = 0;

    for (const row of weighted) {
      let z = bias;
      for (let i = 0; i < dim; i++) z += weights[i] * row.x[i];
      const pred = 1 / (1 + Math.exp(-z));
      const error = (pred - row.y) * row.w;
      for (let i = 0; i < dim; i++) gradW[i] += error * row.x[i];
      gradB += error;
    }

    for (let i = 0; i < dim; i++) weights[i] -= lr * (gradW[i] / totalWeight + l2 * weights[i]);
    bias -= lr * (gradB / totalWeight);
  }
  return { weights, bias };
}

function predictProb(model, x) {
  let z = model.bias;
  for (let i = 0; i < x.length; i++) z += model.weights[i] * x[i];
  return 1 / (1 + Math.exp(-z));
}

// ─── 3. Rule baseline (mirrors the existing keyword logic this replaces) ─
const RULE_KEYWORDS = {
  cheap: ['cheap', 'budget', 'affordable', 'inexpensive', 'low cost', 'reasonable'],
  expensive: ['expensive', 'luxury', 'fine dining', 'high end', 'premium', 'pricy', 'upscale'],
  topRated: ['top rated', 'highest rated', 'best', 'popular', 'famous', 'top 10', 'highly rated', 'excellent', 'greatest'],
  nearMe: ['near me', 'nearby', 'close to me', 'around me', 'close by', 'closest'],
};

function ruleBasedPredict(text) {
  const lower = text.toLowerCase();
  let mood = null;
  for (const [moodKey, keywords] of Object.entries(MOOD_KEYWORDS)) {
    if (lower.includes(moodKey.replace('-', ' ')) || keywords.some((kw) => lower.includes(kw))) {
      mood = moodKey;
      break;
    }
  }
  let price = null;
  if (RULE_KEYWORDS.cheap.some((kw) => lower.includes(kw))) price = 'cheap';
  else if (RULE_KEYWORDS.expensive.some((kw) => lower.includes(kw))) price = 'expensive';
  const isNearMe = RULE_KEYWORDS.nearMe.some((kw) => lower.includes(kw));
  const isTopRated = RULE_KEYWORDS.topRated.some((kw) => lower.includes(kw));
  return { mood, price, isNearMe, isTopRated };
}

// ─── 4. Main ────────────────────────────────────────────────────────────
async function main() {
  const NUM_EXAMPLES = 900;
  const seen = new Set();
  const examples = [];
  while (examples.length < NUM_EXAMPLES) {
    const ex = generateExample();
    const key = ex.text.toLowerCase();
    if (seen.has(key)) continue;
    seen.add(key);
    examples.push(ex);
  }
  console.log(`Generated ${examples.length} unique synthetic queries.`);

  console.log('Embedding queries with local MiniLM model (first run downloads ~90MB, cached after)...');
  for (let i = 0; i < examples.length; i++) {
    examples[i].embedding = await aiService.generateEmbedding(examples[i].text);
    if ((i + 1) % 150 === 0) console.log(`  embedded ${i + 1}/${examples.length}`);
  }
  const dim = examples[0].embedding.length;

  // Split by example, 80/20
  const shuffled = shuffle(examples);
  const splitIdx = Math.floor(shuffled.length * 0.8);
  const train = shuffled.slice(0, splitIdx);
  const test = shuffled.slice(splitIdx);
  console.log(`Train: ${train.length}, Test: ${test.length}`);

  // Train one-vs-rest heads
  const moodModels = {};
  MOOD_KEYS.forEach((key) => {
    const rows = train.map((ex) => ({ x: ex.embedding, y: ex.label.mood === key ? 1 : 0 }));
    moodModels[key] = trainLogisticRegression(rows, dim);
  });
  const priceModels = {};
  PRICE_KEYS.forEach((key) => {
    const rows = train.map((ex) => ({ x: ex.embedding, y: ex.label.price === key ? 1 : 0 }));
    priceModels[key] = trainLogisticRegression(rows, dim);
  });
  const nearMeModel = trainLogisticRegression(train.map((ex) => ({ x: ex.embedding, y: ex.label.isNearMe ? 1 : 0 })), dim);
  const topRatedModel = trainLogisticRegression(train.map((ex) => ({ x: ex.embedding, y: ex.label.isTopRated ? 1 : 0 })), dim);

  const THRESHOLD = 0.5;
  function classifyMood(x) {
    let best = null, bestProb = THRESHOLD;
    for (const key of MOOD_KEYS) {
      const p = predictProb(moodModels[key], x);
      if (p > bestProb) { bestProb = p; best = key; }
    }
    return best;
  }
  function classifyPrice(x) {
    let best = null, bestProb = THRESHOLD;
    for (const key of PRICE_KEYS) {
      const p = predictProb(priceModels[key], x);
      if (p > bestProb) { bestProb = p; best = key; }
    }
    return best;
  }

  // ─── Evaluate: trained model vs rule baseline, same held-out sentences ──
  let trainedCorrect = { mood: 0, price: 0, isNearMe: 0, isTopRated: 0 };
  let ruleCorrect = { mood: 0, price: 0, isNearMe: 0, isTopRated: 0 };

  for (const ex of test) {
    const trainedPred = {
      mood: classifyMood(ex.embedding),
      price: classifyPrice(ex.embedding),
      isNearMe: predictProb(nearMeModel, ex.embedding) > THRESHOLD,
      isTopRated: predictProb(topRatedModel, ex.embedding) > THRESHOLD,
    };
    const rulePred = ruleBasedPredict(ex.text);

    if (trainedPred.mood === ex.label.mood) trainedCorrect.mood++;
    if (trainedPred.price === ex.label.price) trainedCorrect.price++;
    if (trainedPred.isNearMe === ex.label.isNearMe) trainedCorrect.isNearMe++;
    if (trainedPred.isTopRated === ex.label.isTopRated) trainedCorrect.isTopRated++;

    if (rulePred.mood === ex.label.mood) ruleCorrect.mood++;
    if (rulePred.price === ex.label.price) ruleCorrect.price++;
    if (rulePred.isNearMe === ex.label.isNearMe) ruleCorrect.isNearMe++;
    if (rulePred.isTopRated === ex.label.isTopRated) ruleCorrect.isTopRated++;
  }

  const pct = (n) => ((n / test.length) * 100).toFixed(1) + '%';
  console.log('\n=== Accuracy on held-out synthetic test set ===');
  console.log('Slot        | Trained model | Rule baseline');
  console.log('----------- | ------------- | -------------');
  console.log(`mood        | ${pct(trainedCorrect.mood).padEnd(13)} | ${pct(ruleCorrect.mood)}`);
  console.log(`price       | ${pct(trainedCorrect.price).padEnd(13)} | ${pct(ruleCorrect.price)}`);
  console.log(`isNearMe    | ${pct(trainedCorrect.isNearMe).padEnd(13)} | ${pct(ruleCorrect.isNearMe)}`);
  console.log(`isTopRated  | ${pct(trainedCorrect.isTopRated).padEnd(13)} | ${pct(ruleCorrect.isTopRated)}`);

  fs.mkdirSync(OUT_DIR, { recursive: true });
  fs.writeFileSync(
    WEIGHTS_PATH,
    JSON.stringify(
      {
        dim,
        moodModels,
        priceModels,
        nearMeModel,
        topRatedModel,
        threshold: THRESHOLD,
        trainedAt: new Date().toISOString(),
        trainedOn: 'template-generated synthetic queries (see ml/intent-classifier-report.md)',
        metrics: {
          testSize: test.length,
          trained: {
            mood: trainedCorrect.mood / test.length,
            price: trainedCorrect.price / test.length,
            isNearMe: trainedCorrect.isNearMe / test.length,
            isTopRated: trainedCorrect.isTopRated / test.length,
          },
          ruleBaseline: {
            mood: ruleCorrect.mood / test.length,
            price: ruleCorrect.price / test.length,
            isNearMe: ruleCorrect.isNearMe / test.length,
            isTopRated: ruleCorrect.isTopRated / test.length,
          },
        },
      },
      null,
      2
    )
  );
  console.log(`\nSaved weights to ${WEIGHTS_PATH}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
